version: '3'
services:
  web:
    build: './client'
    ports:
      - "3000:3000"

  search:
    build: './server'
    ports:
      - "3001:3000"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./web/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - search
      
